### ISSUE TITLE
An uint64 case is missing for the '%' expression.

### ISSUE THREAD

**Issue by xlab** [cznic/cc#5]
```
panic: internal error: uint64

goroutine 1 [running]:
panic(0x3636a0, 0xc820475170)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cznic/cc.(*Expression).eval(0xc82098c540, 0xc8203563c0, 0x0, 0x0, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/ast2.go:798 +0x56b3
github.com/cznic/cc.(*ExpressionList).eval(0xc820622730, 0xc8203563c0, 0x0, 0x0, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/ast2.go:1457 +0x9d
```

**Comment by cznic** [comment]
https://github.com/cznic/cc/commit/71a6d41217e43ac65aa4b2642b675d7100b0f153 LGTM. Thanks.
