### ISSUE TITLE
Unclosed ifdef causes panic in CC

### ISSUE THREAD

**Issue by xlab** [cznic/cc#50]
Hi! It's not a bug, rather my typo that looks like this:

```C
#ifdef __cplusplus
extern "C";

EOF
```

Not a big deal, but CC crashes with a weird panic that doesn't contribute to finding the root cause.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x1ba214]

goroutine 18 [running]:
panic(0x3a8cc0, 0xc820010110)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cznic/cc.(*pp).preprocessingFile(0xc82020a140, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/cpp.go:982 +0x44
github.com/cznic/cc.Parse.func1(0xc820394120, 0xc82038c5a0, 0xc820390860, 0x68e520, 0xc820075770, 0xc820385ae0, 0xc820396200, 0xc820099780, 0x3, 0x4, ...)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/cc.go:472 +0x350
created by github.com/cznic/cc.Parse
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/cc.go:474 +0xa47
make: *** [all] Error 2
```

**Comment by cznic** [comment]
Thank you for the report.
