### ISSUE TITLE
A binOpType case missing for ULong ULong.

### ISSUE THREAD

**Issue by xlab** [cznic/cc#6]
```
panic: ULong ULong

goroutine 1 [running]:
panic(0x363840, 0xc820481260)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cznic/cc.(*Model).binOpType(0x631b20, 0x708b28, 0xc82095e180, 0x708b28, 0xc820357680, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/model.go:1068 +0x486
github.com/cznic/cc.(*Model).binOp(0x631b20, 0xc8203543c0, 0x70d540, 0xc820958780, 0x70d540, 0xc820958a80, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/model.go:892 +0x12e
```

**Comment by cznic** [comment]
https://github.com/cznic/cc/commit/28c414f37e5322f8a88bf4f8233fccf621385eeb LGTM, thanks.
