### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by pwaller** [cznic/cc#76]
As soon as I merged #73, I realised I had broken the tests:

```
=== RUN   ExampleEnumerator_case1
--- FAIL: ExampleEnumerator_case1 (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19 pc=0x4b2b5e]

goroutine 1 [running]:
panic(0x5fdea0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.runExample.func2(0xecfe0fb27, 0xc439a5e782, 0x77a000, 0xc4203a9ae0, 0xc42002c010, 0xc42044e600, 0x638d19, 0x17, 0x671c10, 0x6513b5, ...)
	/usr/local/go/src/testing/example.go:109 +0x392
panic(0x5fdea0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cznic/cc.(*Model).enumValueToInt(0xc4204cc2c0, 0x5edd00, 0xc4202fe110, 0xc4201c21b8, 0x745e00, 0xc42044e840)
	/home/pwaller/.local/src/github.com/cznic/cc/model.go:164 +0x9e
github.com/cznic/cc.yyParse(0x73af40, 0xc4203c2600, 0xc42030fb90)
	/home/pwaller/.local/src/github.com/cznic/cc/parser.go:4112 +0x175eb
github.com/cznic/cc.exampleAST(0x8c, 0x6381d8, 0x15, 0xc42030fc80, 0xc42030fc88)
	/home/pwaller/.local/src/github.com/cznic/cc/cc.go:218 +0x127a
github.com/cznic/cc.ExampleEnumerator_case1()
	/home/pwaller/.local/src/github.com/cznic/cc/ast_test.go:1468 +0x43
testing.runExample(0x638d19, 0x17, 0x671c10, 0x6513b5, 0x197, 0x0, 0x0)
	/usr/local/go/src/testing/example.go:114 +0x1a0
testing.RunExamples(0x6725b0, 0x775f20, 0x11e, 0x11e, 0x1)
	/usr/local/go/src/testing/example.go:38 +0x15e
testing.(*M).Run(0xc42030fec8, 0xe072)
	/usr/local/go/src/testing/testing.go:744 +0xbd
main.main()
	github.com/cznic/cc/_test/_testmain.go:716 +0xc6
exit status 2
```

I have to go AFK for a while now. Sorry! Will fix it when I get back if I get a moment.

**Comment by cznic** [comment]
Oh sorry, I've fixed already in https://github.com/cznic/cc/commit/0040ed408c08ca4ff7c4866e82e747e9f7b97c62.

My fault to LGTM w/o running tests.

**Comment by cznic** [comment]
:+1:

**Comment by pwaller** [comment]
:+1: thanks. Excellent piece of software, and thanks again for being responsive.

**Comment by cznic** [comment]
> Excellent piece of software...

You're being too generous ;-)

W/o pretending any humbleness, this is one of the packages I'm ashamed most for. Started as a QND hack for literally one-only .c file and it can still be seen all over the code. But is's improving, also b/c of help from others. Thanks!
